### ISSUE TITLE
[Suggestion] Sophisticated Backpack Compat

### ISSUE THREAD

**Issue by Darkosto** [wolforcept/playertabs#3]
Hey!

Would you be willing to look into a compatibility with Sophisticated Backpacks so tabs can be swapped while looking in the backpack GUI? Currently, I have to swap back and forth to change tabs.

![image](https://user-images.githubusercontent.com/10309699/175667801-e4fd8e35-70bf-4754-b7be-5ccd26260b2b.png)

Thank you!
Darkosto
MC: 1.18.2
Forge: 40.1.52
Playertabs: 1.0

**Comment by wolforcept** [comment]
Sure. I've never done it but it should be easy
